### ISSUE TITLE
Connect UART direct to Raspi GPIO

### ISSUE THREAD

**Issue by Tabaluga0815** [MindFreeze/dalybms#5]
Hi, I connected the UART connector from BMS directly to my Raspi GPIO ports , and can read the data via /dev/ttyS0 .
But no luck to use your script to send the data via mqtt to my mqtt iobroker on my windows server.
I would apriciate for some help.
Best wishes
Ralf

**Comment by MindFreeze** [comment]
Sorry but I've only used it through USB. No idea how it would work through gpio pins

**Comment by Tabaluga0815** [comment]
Do you have an idea ?

ralle@raspi-ahoy:~/dalybms $ ./run.sh
Starting BMS monitor...
Traceback (most recent call last):
  File "/home/ralle/.local/lib/python3.9/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: 'null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralle/dalybms/./monitor.py", line 15, in <module>
    ser = serial.Serial(os.environ['DEVICE'])  # open serial port
  File "/home/ralle/.local/lib/python3.9/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/ralle/.local/lib/python3.9/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port null: [Errno 2] No such file or directory: 'null'
